python main.py --prompt "A red bus driving on a desert road" --edit_prompt "A yellow school bus driving on a desert road" --src_img_path "./data/imgs/A_red_bus_driving_on_a_desert_road.png" --loss_type pds --guidance_scale 7.5 --save_dir "./outputs_pds" --step 200
python main.py --prompt "a boat in a river" --edit_prompt "a golden boat in a river" --src_img_path "./data/imgs/a_boat_in_a_river.png" --loss_type pds --guidance_scale 7.5 --save_dir "./outputs_pds" --step 200
python main.py --prompt "A cabin surrounded by forests" --edit_prompt "A cabin surrounded by flowers" --src_img_path "./data/imgs/A_cabin_surrounded_by_forests.png" --loss_type pds --guidance_scale 7.5 --save_dir "./outputs_pds" --step 200
python main.py --prompt "A church beside a lake" --edit_prompt "A church beside a lake at night" --src_img_path "./data/imgs/A_church_beside_a_lake.png" --loss_type pds --guidance_scale 7.5 --save_dir "./outputs_pds" --step 200
python main.py --prompt "A villa close to the pool" --edit_prompt "A villa covered with ivy close to the pool" --src_img_path "./data/imgs/A_villa_close_to_the_pool.png" --loss_type pds --guidance_scale 7.5 --save_dir "./outputs_pds" --step 200
python main.py --prompt "A castle next to a river" --edit_prompt "A rainbow castle next to a river" --src_img_path "./data/imgs/A_castle_next_to_a_river.png" --loss_type pds --guidance_scale 7.5 --save_dir "./outputs_pds" --step 200
python main.py --prompt "A burger on the table" --edit_prompt "A burger with lettuce on the table" --src_img_path "./data/imgs/A_burger_on_the_table.png" --loss_type pds --guidance_scale 7.5 --save_dir "./outputs_pds" --step 200
python main.py --prompt "A dog sitting on grass" --edit_prompt "A golden retriever sitting on grass" --src_img_path "./data/imgs/A_dog_sitting_on_grass.png" --loss_type pds --guidance_scale 7.5 --save_dir "./outputs_pds" --step 200
python main.py --prompt "a cat sitting on a table" --edit_prompt "a wooden cat statue sitting on a table" --src_img_path "./data/imgs/a_cat_sitting_on_a_table.png" --loss_type pds --guidance_scale 7.5 --save_dir "./outputs_pds" --step 200
python main.py --prompt "A car on the road" --edit_prompt "A yellow sportscar on the road" --src_img_path "./data/imgs/A_car_on_the_road.png" --loss_type pds --guidance_scale 7.5 --save_dir "./outputs_pds" --step 200
