python main.py --prompt "A red bus driving on a desert road" --loss_type sds --guidance_scale 25 --save_dir "./outputs_sds"
python main.py --prompt "a boat in a river" --loss_type sds --guidance_scale 25 --save_dir "./outputs_sds"
python main.py --prompt "A cabin surrounded by forests" --loss_type sds --guidance_scale 25 --save_dir "./outputs_sds"
python main.py --prompt "A church beside a lake" --loss_type sds --guidance_scale 25 --save_dir "./outputs_sds"
python main.py --prompt "A villa close to the pool" --loss_type sds --guidance_scale 25 --save_dir "./outputs_sds"
python main.py --prompt "A castle next to a river" --loss_type sds --guidance_scale 25 --save_dir "./outputs_sds"
python main.py --prompt "A burger on the table" --loss_type sds --guidance_scale 25 --save_dir "./outputs_sds"
python main.py --prompt "A dog sitting on grass" --loss_type sds --guidance_scale 25 --save_dir "./outputs_sds"
python main.py --prompt "a cat sitting on a table" --loss_type sds --guidance_scale 25 --save_dir "./outputs_sds"
python main.py --prompt "A car on the road" --loss_type sds --guidance_scale 25 --save_dir "./outputs_sds"
